### ISSUE TITLE
新規参加者へのロール自動付与

### ISSUE THREAD

**Issue by stepney141** [himanoa/uzi#10]
毎回wheelが手動で権限を付与しており、やり忘れなどもあるので、botが自動でやってくれると嬉しい

**Comment by himanoa** [comment]
ロール付けたところで何もないこと考えるとあんまり必要なさそう？

とはいえ色ついてないと寂しいし、新規参加者は付けたくなる気持ちはわかるしやったほうがよさそう

**Comment by himanoa** [comment]
@stepney141 #general に投稿された段階で色が付く みたいな感じが機能の仕様として落とし所がいいような気がしますがどうでしょう？

**Comment by stepney141** [comment]
それでもOKだと思います。

**Comment by himanoa** [comment]
完全自動化するとなると、既存のBotの枠組だと苦しいです。これは内部にcrontabみたいな仕組み持つ必要があるため…

完全なる自動化するとなるとバッチモードとして実装して僕のクラウドのcrontabでバッチを動かすみたいなことをやる必要がある。 = 新しい仕組みを考える必要がある

というのが今渋っているところですねー

**Comment by himanoa** [comment]
>  #general に投稿された段階で色が付く みたいな感じが機能の仕様として落とし所がいいような気がしますがどうでしょう？

この仕組みだとそんなに実装が大変ではない。具体的には
1. Memberのロールを変更するEffectを作る
   2.  Effectful/DiscordMember を新設して作る
2. MessageEventHandlerで発言した人のroleを調べて、付与されてなかったら指定されたロールを付与する
みたいなのをやる、感じなのですが よかったらやってみます？ 

できる限り実装のサポートはします @stepney141

**Comment by stepney141** [comment]
まだHaskellの基本構文をかじっている段階で、言わずもがなあぷりけ

**Comment by himanoa** [comment]
全然急いでないのでゆっくりで大丈夫です～ 🙌

**Comment by himanoa** [comment]
@stepney141 APIドキュメントを整備してみました～よければご参考までに！ https://himanoa.github.io/uzi/uzi-0.2.1.0/

**Comment by stepney141** [comment]
ありがとうございます!
